[package]
name = "lingyunfrp-client-launcher"
version = "1.1.2"
description = "凌云FRP图形化客户端，更方便使用"
authors = ["LYFRP"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.3.1", features = [] }
embed-resource = "3.0.5"

[dependencies]
open = "5.3.2"
reqwest = { version = "0.12.22", features = ["json", "multipart", "blocking"] }
tokio = { version = "1.47.0", features = ["full"] }
tauri = { version = "2.7.0", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.141"
tauri-plugin-notification = "2.3.0"
tauri-plugin-single-instance = "2.3.2"
base64 = "0.22.1"
# 虚拟组网相关依赖
tun = "0.8.3"
# libp2p = "0.52" # 如需复杂P2P可解开
nix = "0.30.1"

lazy_static = "1.4"
runas = "1.1"
rand = "0.9.2"
is_elevated = "0.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
windows = "0.61.3"
wintun = "0.5"
