/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContent: typeof import('./src/components/AppContent.vue')['default']
    CustomContextMenu: typeof import('./src/components/CustomContextMenu.vue')['default']
    HomeMenu: typeof import('./src/components/HomeMenu.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NFlex: typeof import('naive-ui')['NFlex']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NModal: typeof import('naive-ui')['NModal']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NProgress: typeof import('naive-ui')['NProgress']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistic: typeof import('./src/components/Statistic.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    WelcomeCard: typeof import('./src/components/WelcomeCard.vue')['default']
  }
}
